version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - PORT=8000

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - PORT=3000
